Added QuickSort
4ndrelim/data-structures-and-algorithms pull request #25
Opened 2023-07-31 10:26 UTC by kaitinghh

2023-08-15 16:02 UTC, 4ndrelim requested changes
Overall great, minor changes.

2023-08-26 06:51 UTC, kaitinghh commented on src/algorithms/sorting/quickSort/hoares/README.md
> +merely partitions the array into <= pivot and >= pivot portions.
The description and analysis above assumes no duplicates. But the implementation/code itself can handle duplicates (puts them to left of pivot).

2023-08-26 10:13 UTC, kaitinghh commented on src/algorithms/sorting/quickSort/hoares/QuickSort.java
> +        while (low <= high) {
mm yeah, it was necessary bc of the way I implemented previously. but I changed to another implementation (increment/decrement pointer before comparing element value w pivot), so now low < high is sufficient

2023-08-26 10:13 UTC, kaitinghh commented on src/algorithms/sorting/quickSort/hoares/README.md
> +Time:
I think is O(logn)?

2023-08-27 06:07 UTC, 4ndrelim approved these changes
LGTM, but pending some comments from kaiting.

2023-08-27 07:30 UTC, merged