Branch mst adjmatrix
4ndrelim/data-structures-and-algorithms pull request #80
Opened 2024-03-26 14:46 UTC by junnengsoo

2024-04-04 14:19 UTC, 4ndrelim requested changes
Not done yet, ill update on Friday after i tweak Disjoint Set implementation to better handle duplicates and to be more portable!

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/kruskal/Edge.java
> +package algorithms.minimumSpanningTree.kruskal;
our other files typically place helper class in the same file. For consistency sake, we could shift this to Kruskal.java too. But if there are any concerns do bring it up!

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/kruskal/DisjointSet.java
> +    public DisjointSet(Node[] listOfNodes) {
nice, but we should align our implementation of disjoint set. There already is an existing one which u can either import or copy-paste (maybe this is preferable? to be explicit).

Ok but i did notice a concern as i was looking through. Both urs and my implementation does not handle duplicates well. I will tweak the official DisjointSet implementation of our repo to identify by memory address instead.

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/kruskal/Kruskal.java
> +        return mstMatrix;
cant rmb if this was what we discussed. But we do this just as a representation to capture the edges right? Do you know of any online helper functions to visualise the mst lol

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/kruskal/Kruskal.java
> +public class Kruskal {
overall logic is neat and clear! thanks!

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/kruskal/Node.java
> +package algorithms.minimumSpanningTree.kruskal;
yup same for this class also. Maybe can put at the bottom as helper classes

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/prim/Prim.java
> +        PriorityQueue<Node> pq = new PriorityQueue<>((a, b) -> a.getCurrMinWeight() - b.getCurrMinWeight());
maybe a small helper comment to remind its a min-heap

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/prim/Prim.java
> +        int[] parent = new int[nodes.length]; // To track the parent node of each node in the MST
nice. Map<> works too but i think array is even simpler.

2024-04-04 14:19 UTC, 4ndrelim commented on src/main/java/algorithms/minimumSpanningTree/prim/Prim.java
> +package algorithms.minimumSpanningTree.prim;
i believe the underlying assumption is that the graph is connected right? i think both ur implementation should work fine for unconnected graphs too (not a thorough analysis.. jsut a quick run-through in my head) - that is, your return matrix should capture separate MSTs, if exist. Do double check and lmk if im wrong!

2024-04-09 16:27 UTC, 4ndrelim commented
@junnengsoo can we close this?

2024-04-16 16:29 UTC, junnengsoo commented
A separate PR for MST was merged to main.

2024-04-16 16:29 UTC, closed without merging